name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Create version bump with Changesets
        run: npx changeset version

      - name: Re-install after version bump
        run: npm install

      - name: Publish to npm
        run: npx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version bump and changelog
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "svenkatreddy"
          git config --global user.email "svenkatreddy@users.noreply.github.com"
          git remote add release-origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "chore: release new version" || echo "No changes to commit"
          git push release-origin HEAD:main
